sudo: required
archlinux:
    packages:
    - startup-notification
    - libxml2
    - libxinerama
    - libxrandr
    - libxcursor
    - pango
    - imlib2
    - librsvg
    - libsm
    script:
      - "makepkg -s"
script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
