post_install() {
    echo
    echo "==> To enable Rounded Corners add this line to the \'<theme>\' section of your Openbox config."
    echo "==> \'<cornerRadius>8</cornerRadius>\'"
    echo "==> The patch also takes an argument for menu corners."
    echo "==> \'<cornerRadius menu=\"yes\">8</cornerRadius>\'"
    echo
    echo "==> Report bugs or feature requests here:"
    echo "==> https://github.com/dylanaraps/openbox-patched"
    echo
}
